# This is a workflow to build with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
    - '**'
    tags:
    - 'prod-*.*'
  # pull_request:
  #   branches:
  #     - 'master'
  #   tags:
  #     - 'v*.*.*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-api-uvarc-io:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set the emv
      id: set_env
      run: echo "BUILD_PROJ=api.uvarc.io" >> $GITHUB_ENV
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]quay.io/uvarc/${{ env.BUILD_PROJ }}:$(echo ${GITHUB_REF##*/})"
      id: extract_branch
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub/Quay
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
    - name: Build and push
      if: github.ref == 'refs/heads/master'
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ steps.extract_branch.outputs.branch }}
          quay.io/uvarc/${{ env.BUILD_PROJ }}:latest
    - name: Build and push
      if: github.ref != 'refs/heads/master'
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ steps.extract_branch.outputs.branch }}
